### ISSUE TITLE
How to generate near-field channel in O1-140 scenario?

### ISSUE THREAD

**Issue by Meblus199478** [DeepMIMO/DeepMIMO-python#1]
I need to conduct some near-field research in O1-140 scenario, but I find it only supports far-field scenario, so I wanna code to generate near-field channel via the parameters in O1-140 scenario.

**Comment by jmoraispk** [comment]
Hi @Meblus199478 

My sincere apologies for the delay. Our notifications for this were not enabled. 

Near-field channels are not currently supported in DeepMIMO. DeepMIMO makes a far-field approximation to expand the number of antennas used in a raytracing scenario, and the channel model follows such an approximation.

Let us know if we can help further.
