### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ericphilbaz** [DeepMIMO/DeepMIMO-python#2]
for python:
[Errno 2] No such file or directory: '======================\DeepMIMO_pro\\scenarios\\O1_60\\O1_60.params.mat'

**Comment by umut-demirhan** [comment]
Hi @ericphilbaz 

It seems that either a) the scenario is not installed correctly, or b) the scenario folder parameter is not set correctly. 

To install the scenario, you need to download the O1_60 scenario zip file from [here](https://www.deepmimo.net/scenarios/o1-scenario/), and extract it to "=====\DeepMIMO_pro\scenarios" folder. After the installation, you should have the file 'O1_60\O1_60.params.mat' at the desired path.
