### ISSUE TITLE
How to customize a scenarios by ourselves?

### ISSUE THREAD

**Issue by TailinZhou** [DeepMIMO/DeepMIMO-python#3]
Dear, this is great open-source work. 

Could we customize a scenario by ourselves? If yes, how do we customize a scenario? If not, do you mind introducing more about how to get the .mat files for a scenario?

Many thanks.

**Comment by jmoraispk** [comment]
Hi @TailinZhou 

Apologies for the late reply. I had not set the proper notifications on this. 

What customization are you looking for? Note that DeepMIMO already provides many tools to customize your data. These include changing the number of antennas, user positions, frequency, bandwidth, etc. You can see examples of them in [DeepMIMO website](https://www.deepmimo.net/versions/deepmimo-v3-python/).

If those are not sufficient, you might need to raytrace the scenario yourself and convert it to the DeepMIMO format for convenient processing. We are actively creating DeepMIMO scenarios, so if your scenario makes sense for a wider audience, we might be able to compute those simulations for you.
